import type { ConsolePayload } from './types';

export const mockConsoleData: ConsolePayload = {
  status: {
    adapters: 1,
    plugins: 3,
    jobs: 2,
    schedules: 1,
  },
  adapters: [
    {
      id: 'adapter-onebot-demo',
      adapter: 'onebot',
      source: 'onebot',
      config: {
        demo_path: '/demo/onebot/message',
        platform: 'onebot/v11',
        source: 'onebot',
      },
      status: 'registered',
      health: 'ready',
      online: true,
      statusSource: 'sqlite-adapter-instances',
      configSource: 'sqlite-adapter-instances',
      statePersisted: true,
      updatedAt: '2026-04-19T11:58:00Z',
      summary: 'adapter instance adapter-onebot-demo for onebot/onebot is registered with health=ready via sqlite-adapter-instances; persisted state survives restart; online=online',
    },
  ],
  alerts: [
    {
      id: 'job.dead_letter:job-dead-letter-console',
      objectType: 'job',
      objectId: 'job-dead-letter-console',
      failureType: 'job.dead_letter',
      firstOccurredAt: '2026-04-19T11:55:00Z',
      latestOccurredAt: '2026-04-19T11:55:00Z',
      latestReason: 'worker abandoned during timeout recovery',
      traceId: 'trace-job-dead-letter-console',
      eventId: 'evt-job-dead-letter-console',
      runId: 'job-dead-letter-console',
      correlation: 'corr-dead-letter-console',
      createdAt: '2026-04-19T11:55:00Z',
    },
  ],
  replayOps: [
    {
      replayId: 'replay-console-1',
      sourceEventId: 'evt-source-console-1',
      replayEventId: 'replay-evt-source-console-1-1',
      status: 'succeeded',
      reason: 'replay_dispatched',
      occurredAt: '2026-04-19T11:40:00Z',
      updatedAt: '2026-04-19T11:40:00Z',
      stateSource: 'sqlite-replay-operation-records',
      persisted: true,
      summary: 'replay succeeded source=evt-source-console-1 result=replay-evt-source-console-1-1 | via sqlite-replay-operation-records | reason=replay_dispatched',
    },
  ],
  rolloutOps: [
    {
      operationId: 'rollout-console-1',
      pluginId: 'plugin-echo',
      action: 'prepare',
      currentVersion: '0.1.0',
      candidateVersion: '0.2.0-candidate',
      status: 'prepared',
      reason: 'prepared-record-required',
      occurredAt: '2026-04-19T11:41:00Z',
      updatedAt: '2026-04-19T11:41:00Z',
      stateSource: 'sqlite-rollout-operation-records',
      persisted: true,
      summary: 'rollout prepare prepared for plugin-echo | current=0.1.0 candidate=0.2.0-candidate | via sqlite-rollout-operation-records | reason=prepared-record-required',
    },
  ],
  rolloutHeads: [
    {
      pluginId: 'plugin-echo',
      stable: {
        version: '0.1.0',
        apiVersion: 'v0',
        mode: 'subprocess',
      },
      active: {
        version: '0.2.0-candidate',
        apiVersion: 'v0',
        mode: 'subprocess',
      },
      candidate: {
        version: '0.2.0-candidate',
        apiVersion: 'v0',
        mode: 'subprocess',
      },
      phase: 'canary',
      status: 'canarying',
      lastOperationId: 'rollout-console-1',
      updatedAt: '2026-04-19T11:41:00Z',
      stateSource: 'sqlite-rollout-heads',
      persisted: true,
      summary: 'rollout head canary canarying for plugin-echo | stable=0.1.0 active=0.2.0-candidate | candidate=0.2.0-candidate | via sqlite-rollout-heads | last_operation=rollout-console-1',
    },
  ],
  plugins: [
    {
      id: 'plugin-echo',
      name: 'Echo Plugin',
      version: '0.1.0',
      apiVersion: 'v0',
      mode: 'subprocess',
      permissions: ['message:read'],
      configSchema: {
        type: 'object',
        properties: {
          prefix: { type: 'string' },
        },
      },
      config: { prefix: 'persisted: ' },
      publish: {
        sourceType: 'git',
        sourceUri: 'https://github.com/ohmyopencode/bot-platform/tree/main/plugins/plugin-echo',
        runtimeVersionRange: '>=0.1.0 <1.0.0',
      },
      entry: { module: 'plugins/plugin-echo' },
      configStateKind: 'plugin-owned-persisted-input',
      configSource: 'sqlite-plugin-config',
      configPersisted: true,
      configUpdatedAt: '2026-04-19T11:42:00Z',
      enabled: true,
      enabledStateSource: 'runtime-default-enabled',
      enabledStatePersisted: false,
      statusSource: 'runtime-registry+runtime-dispatch-results',
      statusEvidence: 'runtime-dispatch-result:instance-config-reject',
      statusSummary: 'last runtime event dispatch was rejected before subprocess launch via runtime-registry+runtime-dispatch-results; stage=instance-config; recovery=last-dispatch-failed; evidence=process-local-volatile',
      runtimeStateLive: true,
      statusPersisted: false,
      lastDispatchKind: 'event',
      lastDispatchSuccess: false,
      lastDispatchError: 'plugin host dispatch "plugin-echo": plugin "plugin-echo" instance config required property "prefix" must be provided',
      lastDispatchAt: '2026-04-19T11:59:00Z',
      lastRecoveredAt: '2026-04-19T11:57:00Z',
      lastRecoveryFailureCount: 2,
      currentFailureStreak: 1,
      statusLevel: 'error',
      statusRecovery: 'last-dispatch-failed',
      statusStaleness: 'process-local-volatile',
    },
    {
      id: 'plugin-admin',
      name: 'Admin Plugin',
      version: '0.2.0',
      apiVersion: 'v0',
      mode: 'subprocess',
      permissions: [],
      entry: { module: 'plugins/plugin-admin' },
      enabled: true,
      enabledStateSource: 'runtime-default-enabled',
      enabledStatePersisted: false,
      statusSource: 'runtime-registry',
      statusEvidence: 'manifest-only',
      statusSummary: 'manifest registered without live runtime evidence yet',
      runtimeStateLive: false,
      statusPersisted: false,
      statusLevel: 'registered',
      statusRecovery: 'no-runtime-evidence',
      statusStaleness: 'static-registration',
    },
    {
      id: 'plugin-workflow-demo',
      name: 'Workflow Demo',
      version: '0.1.0',
      apiVersion: 'v0',
      mode: 'inproc',
      permissions: ['workflow:read'],
      entry: { module: 'plugins/plugin-workflow-demo' },
      enabled: true,
      enabledStateSource: 'runtime-default-enabled',
      enabledStatePersisted: false,
      statusSource: 'runtime-registry',
      statusEvidence: 'manifest-only',
      statusSummary: 'manifest registered without live runtime evidence yet',
      runtimeStateLive: false,
      statusPersisted: false,
      statusLevel: 'registered',
      statusRecovery: 'no-runtime-evidence',
      statusStaleness: 'static-registration',
    },
  ],
  jobs: [
    {
      id: 'job-dead-letter-console',
      type: 'ai.chat',
      traceId: 'trace-job-dead-letter-console',
      eventId: 'evt-job-dead-letter-console',
      runId: 'job-dead-letter-console',
      status: 'dead',
      payload: {
        dispatch: {
          actor: 'runtime-job-runner',
          permission: 'job:run',
          target_plugin_id: 'plugin-ai-chat',
        },
        prompt: 'hello retry',
        session_id: 'session-user-retry',
      },
      retryCount: 1,
      maxRetries: 1,
      timeout: 30000000000,
      lastError: 'worker abandoned during timeout recovery',
      createdAt: '2026-04-19T11:50:00Z',
      startedAt: '2026-04-19T11:51:00Z',
      finishedAt: '2026-04-19T11:55:00Z',
      nextRunAt: null,
      workerId: 'runtime-local:demo',
      leaseAcquiredAt: '2026-04-19T11:51:00Z',
      leaseExpiresAt: '2026-04-19T11:51:30Z',
      heartbeatAt: '2026-04-19T11:51:20Z',
      reasonCode: 'worker_abandoned',
      deadLetter: true,
      correlation: 'corr-dead-letter-console',
      targetPluginId: 'plugin-ai-chat',
      dispatchMetadataPresent: true,
      dispatchContractPresent: true,
      queueContractComplete: true,
      dispatchReady: false,
      queueStateSummary: 'dead-lettered',
      dispatchSummary: 'dispatch actor runtime-job-runner targeting plugin-ai-chat with permission job:run',
      queueContractSummary: 'dispatch actor runtime-job-runner targeting plugin-ai-chat with permission job:run | reply via onebot.reply to group-42',
      leaseSummary: 'lease runtime-local:demo expired after runtime restart recovery',
      dispatchPermission: 'job:run',
      dispatchActor: 'runtime-job-runner',
      dispatchRbac: {
        actor: 'runtime-job-runner',
        permission: 'job:run',
        targetPluginId: 'plugin-ai-chat',
        dispatchKind: 'job',
        runtimeAuthorizerEnabled: true,
        runtimeAuthorizerScope: 'job-metadata-runtime-authorizer',
        manifestGateEnabled: true,
        manifestGateScope: 'dispatch-manifest-permission-gate',
        jobTargetFilterEnabled: true,
        facts: ['actor=runtime-job-runner', 'permission=job:run', 'target_plugin_id=plugin-ai-chat'],
        summary: 'job metadata dispatch authorizer uses actor/permission/target_plugin_id before queued runtime dispatch',
      },
      replyHandlePresent: true,
      replyHandleCapability: 'onebot.reply',
      replyContractPresent: true,
      replySummary: 'reply via onebot.reply to group-42',
      sessionIDPresent: true,
      replyTargetPresent: true,
      recoverySummary: 'reason_code=worker_abandoned worker=runtime-local:demo lease expired before restart recovery',
    },
    {
      id: 'job-console-ready',
      type: 'ai.chat',
      status: 'pending',
      payload: {},
      retryCount: 0,
      maxRetries: 1,
      timeout: 30000000000,
      lastError: '',
      createdAt: '2026-04-19T11:58:00Z',
      startedAt: null,
      finishedAt: null,
      nextRunAt: null,
      deadLetter: false,
      correlation: 'corr-console-ready',
      dispatchReady: true,
      queueStateSummary: 'ready',
      recoverySummary: '',
    },
  ],
  schedules: [
    {
      id: 'schedule-console',
      kind: 'delay',
      source: 'runtime-demo-scheduler',
      eventType: 'message.received',
      cronExpr: '',
      delayMs: 30000,
      executeAt: null,
      dueAt: '2026-04-19T12:01:00Z',
      dueAtSource: 'persisted-state',
      dueAtEvidence: 'persisted-schedule-due-at',
      dueAtPersisted: true,
      dueReady: false,
      overdue: false,
      claimOwner: '',
      claimedAt: null,
      claimed: false,
      recoveryState: '',
      dueStateSummary: 'scheduled',
      dueSummary: 'delay scheduled at 2026-04-19T12:01:00Z (persisted dueAt)',
      scheduleSummary: 'message.received | delay scheduled at 2026-04-19T12:01:00Z (persisted dueAt)',
      createdAt: '2026-04-19T11:59:00Z',
      updatedAt: '2026-04-19T11:59:00Z',
    },
  ],
  workflows: [
    {
      id: 'workflow-user-1',
      pluginId: 'plugin-workflow-demo',
      traceId: 'trace-workflow-console',
      eventId: 'evt-workflow-console-origin',
      runId: 'run-workflow-console',
      correlationId: 'corr-workflow-console',
      status: 'waiting_event',
      currentIndex: 1,
      waitingFor: 'message.received',
      sleepingUntil: null,
      completed: false,
      compensated: false,
      state: {
        greeting: 'hello',
        step: 'awaiting follow-up',
      },
      lastEventId: 'evt-workflow-console',
      lastEventType: 'message.received',
      statusSource: 'sqlite-workflow-instances',
      statePersisted: true,
      runtimeOwner: 'runtime-core',
      createdAt: '2026-04-19T11:48:00Z',
      updatedAt: '2026-04-19T11:58:00Z',
      summary: 'workflow workflow-user-1 for plugin-workflow-demo is waiting_event via sqlite-workflow-instances; waiting_for=message.received; persisted state survives restart',
    },
  ],
  logs: [
    '2026-04-19T11:58:00Z INFO runtime started',
    '2026-04-19T11:59:00Z WARN plugin-echo instance config missing prefix',
    '2026-04-19T12:00:00Z ERROR job-dead-letter-console dead letter after worker recovery',
  ],
  audits: [
    {
      actor: 'admin-user',
      permission: 'plugin:disable',
      action: 'disable',
      target: 'plugin-echo',
      allowed: true,
      reason: 'plugin_disabled',
      trace_id: 'trace-console-audit-plugin-disable',
      event_id: 'evt-console-audit-plugin-disable',
      plugin_id: 'plugin-echo',
      run_id: 'run-console-audit-plugin-disable',
      session_id: 'session-operator-bearer-admin-user',
      correlation_id: 'corr-console-audit-plugin-disable',
      error_category: 'operator',
      error_code: 'plugin_disabled',
      occurred_at: '2026-04-19T11:43:00Z',
    },
    {
      actor: 'config-operator',
      permission: 'plugin:config',
      action: 'config.update',
      target: 'plugin-echo',
      allowed: true,
      reason: 'plugin_config_updated',
      trace_id: 'trace-console-audit-plugin-config',
      event_id: 'evt-console-audit-plugin-config',
      plugin_id: 'plugin-echo',
      run_id: 'run-console-audit-plugin-config',
      session_id: 'session-operator-bearer-config-operator',
      correlation_id: 'corr-console-audit-plugin-config',
      error_category: 'operator',
      error_code: 'plugin_config_updated',
      occurred_at: '2026-04-19T11:42:00Z',
    },
    {
      actor: 'job-operator',
      permission: 'job:retry',
      action: 'retry',
      target: 'job-dead-letter-console',
      allowed: true,
      reason: 'job_dead_letter_retried',
      trace_id: 'trace-console-audit-job-retry',
      event_id: 'evt-console-audit-job-retry',
      run_id: 'run-console-audit-job-retry',
      session_id: 'session-operator-bearer-job-operator',
      correlation_id: 'corr-console-audit-job-retry',
      error_category: 'operator',
      error_code: 'job_dead_letter_retried',
      occurred_at: '2026-04-19T11:56:00Z',
    },
  ],
  config: {
    Runtime: {
      Environment: 'development',
      LogLevel: 'debug',
      HTTPPort: 8080,
    },
    RBAC: {
      ActorRoles: {
        'viewer-user': ['console-viewer'],
        'admin-user': ['admin', 'console-viewer'],
        'config-operator': ['plugin-config-operator', 'console-viewer'],
        'job-operator': ['job-operator', 'console-viewer'],
        'schedule-admin': ['schedule-operator', 'console-viewer'],
      },
      Policies: {
        'console-viewer': {
          permissions: ['console:read'],
          pluginScope: ['console'],
        },
        admin: {
          permissions: ['plugin:enable', 'plugin:disable', 'plugin:rollout'],
          pluginScope: ['*'],
        },
        'plugin-config-operator': {
          permissions: ['plugin:config'],
          pluginScope: ['plugin-echo'],
        },
        'job-operator': {
          permissions: ['job:retry'],
          pluginScope: ['*'],
        },
        'schedule-operator': {
          permissions: ['schedule:cancel'],
          pluginScope: ['*'],
        },
      },
      ConsoleReadPermission: 'console:read',
    },
  },
  meta: {
    runtime_entry: 'apps/runtime',
    demo_paths: [
      '/demo/onebot/message',
      '/demo/ai/message',
      '/demo/jobs/enqueue',
      '/demo/jobs/{job-id}/retry',
      '/demo/schedules/echo-delay',
      '/demo/schedules/{schedule-id}/cancel',
      '/demo/plugins/{plugin-id}/enable',
      '/demo/plugins/{plugin-id}/disable',
      '/demo/plugins/{plugin-id}/config',
      '/demo/replies',
      '/demo/state/counts',
    ],
    sqlite_path: 'data/dev/runtime.sqlite',
    scheduler_interval_ms: 100,
    ai_job_dispatcher_registered: true,
    console_mode: 'read+operator-plugin-enable-disable+plugin-config+job-retry+schedule-cancel',
    generated_at: '2026-04-19T12:00:00Z',
    plugin_operator_actions: ['/demo/plugins/{plugin-id}/enable', '/demo/plugins/{plugin-id}/disable'],
    plugin_operator_scope: 'already-registered plugins only',
    plugin_config_operator_actions: ['/demo/plugins/{plugin-id}/config'],
    plugin_config_operator_scope: 'plugins with app-local persisted config bindings only',
    job_operator_actions: ['/demo/jobs/{job-id}/retry'],
    job_operator_scope: 'dead-letter jobs only',
    schedule_operator_actions: ['/demo/schedules/{schedule-id}/cancel'],
    schedule_operator_scope: 'currently-registered schedules only',
    rbac_console_read_actor_header: 'X-Bot-Platform-Actor',
    rbac_console_read_permission: true,
    request_identity: {
      actor_id: 'viewer-user',
      token_id: 'viewer-main',
      auth_method: 'bearer',
      session_id: 'session-operator-bearer-viewer-user',
    },
    rbac_console_limitations: [
      'console read authorization uses bearer-backed request identity when operator_auth.tokens is configured; otherwise it falls back to the X-Bot-Platform-Actor header',
      'current slice persists and reloads a single runtime snapshot but does not add login/authn UX or a global resource hierarchy',
    ],
    rollout_policy: {
      entryPoints: ['/admin prepare <plugin-id>', '/admin activate <plugin-id>'],
      preflightChecks: ['manifest.id-match', 'manifest.mode-match', 'manifest.api-version-match', 'manifest.version-changed'],
      activationChecks: ['prepared-record-required', 'prepare-time-drift-recheck', 'lifecycle-enable-before-activated-mark'],
      auditReasons: ['rollout_prepared', 'rollout_activated', 'rollout_drifted', 'rollout_failed'],
      recordStore: 'sqlite-current-runtime-rollout-operations',
      supportedModes: ['manual-prepare-activate', 'manifest-preflight', 'activate-time-drift-recheck', 'minimal-audit-reasons'],
      unsupportedModes: [
        'rollback',
        'staged-rollout',
        'health-check-gate',
        'automatic-rollback',
        'persisted-rollout-history',
        'approval-workflow',
        'schema-migration-gate',
      ],
      verificationEndpoints: ['GET /api/console', 'go test ./packages/runtime-core ./plugins/plugin-admin ./apps/runtime -run Rollout'],
      facts: [
        'rollout is currently a manual admin chain limited to /admin prepare <plugin-id> and /admin activate <plugin-id>',
        'prepare records only minimal manifest compatibility facts for ID, Mode, APIVersion, and Version change',
        'activate re-checks current and candidate manifests before lifecycle enable so prepare-time drift is rejected',
        'rollout prepare and activate attempts are persisted as operational records and remain visible after restart',
      ],
      summary:
        'manual /admin prepare|activate only; preflight checks ID|Mode|APIVersion|Version; activate re-checks drift before lifecycle enable; rollout attempts persist as operational records; audit reasons are minimal; no rollback or staged rollout',
    },
    rollout_record_store: 'sqlite-current-runtime-rollout-operations',
    rollout_record_read_model: 'sqlite-rollout-operation-records',
    rollout_record_persisted: true,
    rollout_head_read_model: 'sqlite-rollout-heads',
    rollout_head_persisted: true,
    rollout_console_limitations: [
      'rollout policy declaration is read-only and mirrors existing runtime behavior only',
      'rollout remains limited to manual /admin prepare|activate with minimal manifest preflight and activate-time drift re-check; no rollback or staged rollout',
    ],
    verification_endpoints: ['GET /api/console', 'GET /metrics', 'GET /demo/state/counts'],
  },
  recovery: {
    recoveredAt: '2026-04-19T11:45:00Z',
    totalJobs: 2,
    recoveredJobs: 1,
    recoveredRunning: 1,
    retriedJobs: 1,
    deadJobs: 1,
    statusCounts: {
      retrying: 1,
      dead: 1,
    },
    totalSchedules: 1,
    recoveredSchedules: 1,
    invalidSchedules: 0,
    scheduleKinds: {
      delay: 1,
    },
    summary: 'jobs_restored=2 running_recovered=1 retrying=1 dead=1 schedules_restored=1 schedules_recovered=1 at=2026-04-19T11:45:00Z',
  },
  observability: {
    jobDispatchReady: 1,
    scheduleDueReady: 0,
    jobStateSource: 'sqlite-jobs',
    scheduleStateSource: 'sqlite-schedule-plans',
    logStateSource: 'runtime-log-buffer',
    traceStateSource: 'runtime-trace-recorder',
    metricsStateSource: 'runtime-metrics-registry',
    verificationEndpoints: ['GET /api/console', 'GET /metrics', 'GET /demo/state/counts'],
    alertability: {
      baseline: [
        {
          id: 'repeated_dispatch_failures',
          severity: 'error',
          signal: 'plugins[].currentFailureStreak + plugins[].statusSummary',
          condition: 'currentFailureStreak >= 2 means repeated dispatch failures are already visible in the repo-local console payload',
          verificationEndpoints: ['GET /api/console', 'GET /metrics'],
          summary: 'operators can verify repeated dispatch failures from plugin status summaries, failure streaks, and the existing runtime/subprocess dispatch metrics families',
        },
        {
          id: 'ready_backlog',
          severity: 'warn',
          signal: 'observability.jobDispatchReady + observability.scheduleDueReady + bot_platform_queue_lag',
          condition: 'non-zero ready job or due schedule counts expose a repo-local backlog snapshot; repeated reads show whether it is draining',
          verificationEndpoints: ['GET /api/console', 'GET /metrics'],
          summary: 'operators can verify queue lag and ready backlog locally from the console snapshot and Prometheus-style metrics without an external monitoring stack',
        },
        {
          id: 'subprocess_failure_classified',
          severity: 'error',
          signal: 'plugins[].statusSummary + plugins[].lastDispatchError + bot_platform_subprocess_failure_total',
          condition: 'subprocess plugin failures stay locally classifiable through existing status summaries and subprocess failure metric labels',
          verificationEndpoints: ['GET /api/console', 'GET /metrics'],
          summary: 'operators can verify subprocess failure stage/reason evidence from plugin status summaries and subprocess failure metric families already emitted by runtime-core',
        },
        {
          id: 'dead_letter_failure_paths',
          severity: 'error',
          signal: 'alerts[].failureType=job.dead_letter + alerts[].latestReason + jobs[].replySummary/recoverySummary',
          condition: 'dead-letter alerts preserve the latest repo-local failure reason for reply, upstream, timeout, and adjacent operator-visible failure paths',
          verificationEndpoints: ['GET /api/console', 'GET /demo/state/counts', 'GET /demo/replies'],
          summary: 'operators can verify dead-letter failure paths from persisted alert records and the current console job/reply surfaces without external alert routing',
        },
      ],
      activeFindings: [
        {
          ruleId: 'ready_backlog',
          severity: 'warn',
          status: 'firing',
          summary: 'ready backlog present; job_dispatch_ready=1 schedule_due_ready=0',
          evidence: ['job_dispatch_ready=1', 'schedule_due_ready=0', 'ready_jobs=job-1'],
        },
      ],
      summary: '4 rules 1 active findings via repo-local console/metrics surfaces',
    },
    summary: 'jobs=sqlite-jobs ready=1 | schedules=sqlite-schedule-plans due=0 | metrics=runtime-metrics-registry | logs=runtime-log-buffer | traces=runtime-trace-recorder | alertability=4 rules 1 active findings via repo-local console/metrics surfaces',
  },
};

export function cloneMockConsoleData(): ConsolePayload {
  return JSON.parse(JSON.stringify(mockConsoleData)) as ConsolePayload;
}
